### ISSUE TITLE
compile on Mac

### ISSUE THREAD

**Issue by ibayer** [ibayer/fastFM-core#1] opened 2015-05-14 08:02 UTC
```
Rockys-MacBook-Pro:fastFM rockyrock$ make
( cd fastFM-core ; /Applications/Xcode.app/Contents/Developer/usr/bin/make lib )
( cd src ; /Applications/Xcode.app/Contents/Developer/usr/bin/make lib )
c99 `pkg-config --cflags glib-2.0` -fPIC -g -Wall -O3 -I/include -I./src -I../externals/CXSparse/Include   -c -o kmath.o kmath.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c99: illegal option -- f
usage: c99 [-cEgs] [-D name[=value]] [-I directory] ... [-L directory] ...
       [-o outfile] [-O optlevel] [-U name]... [-W 64] operand ...
make[2]: *** [kmath.o] Error 1
make[1]: *** [lib] Error 2
make: *** [all] Error 2
```

@rakandirbas
Thanks for reporting this issue for fastFM (py). I think it's best to solve the issue for fastFM-core first and then move on to the python interface.

**Comment by ibayer** [comment] 2015-05-14 08:14
This looks like a compiler flag issue to me (but I'm not experienced with Mac dev tools).
`c99 `pkg-config --cflags glib-2.0` -fPIC -g -Wall -O3 -I/include -I./src -I../externals/CXSparse/Include   -c -o kmath.o kmath.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c99: illegal option -- f`

I'm using `pkg-config` in the makefile. Is this tool installed on your machine?
// see `/fastFM-core/src/Makefile`

```
CFLAGS = `pkg-config --cflags glib-2.0` -fPIC -g -Wall -O3 -I/include -I./src -I../externals/CXSparse/Include
```

**Comment by rakandirbas** [comment] 2015-05-14 09:41
Yes I do have `pkg-config`. This is what I get from `man pkg-config`:

`The pkg-config program is used to retrieve information about  installed
       libraries  in  the  system.   It  is typically used to compile and link
       against one or more libraries.  Here is a typical usage scenario  in  a
       Makefile: ...`

**Comment by kidexp** [comment] 2015-07-26 13:39
Any updates on this? face same issue.
Thanks

**Comment by ibayer** [comment] 2015-07-26 21:39
Not really, I'm still hoping that someone with Mac development experience helps out.
I won't have time to look into it before end of September.

**Comment by altimin** [comment] 2015-07-28 11:37
Managed to compile it on Mac.

The reason behind this error is that gcc-specific options are used (-fPIC and -Wall), which are not available in c99 compiler. This options can be removed or CC=gcc can be used instead.

There are another issue in src/ffm_utils.c:204: nested functions are not included in standard C and many compilers do not support it. Both c99 compiler and gcc (provided by clang on OS X) do not support nested functions. But this can easily be fixed.

And the last small issue is that there is no <args.h> by default on OS X, but this can be fixed by `brew install args-standalone` (I think that this library should be listed in dependencies).

**Comment by kidexp** [comment] 2015-07-28 11:44
Thanks very much for the updates.

**Comment by ibayer** [comment] 2015-07-28 15:40
@altimin 
Thanks for helping out, that’s much appreciated!

I'm happy to accept pull requests if one of you wants to open one.

**Comment by altimin** [comment] 2015-07-28 16:22
@ibayer
No problem, I'm glad to be able to contribute. I will create a pull request tomorrow.

**Comment by altimin** [comment] 2015-07-29 07:48
I've created a pull request.

However, I've realised that yesterday I only compiled lib, not cli. The problem is that there are no `feenableexcept` function on OSX. I wonder if everything will still work if I disable this function on OSX.

Another question is about atlas library. It is linked against, but it looks like it is not used.

**Comment by ibayer** [comment] 2015-07-29 15:50
`feenableexcept` is only used in the tests it helps to locate floating point errors. Can we use a preprocessor directive to skip it when compiling on  OSX? This shouldn't affect the cli. 

The atlas library includes BLAS which is used in fastFM. It would be okay to use a different BLAS implementation on OSX. I'm using atlas because it contains a fast BLAS implementation..

**Comment by ibayer** [comment] 2015-08-09 05:56
@rakandirbas 
Can you confirm that the lib compile now on OSX (see instruction in readme)?

**Comment by rakandirbas** [comment] 2015-08-09 09:16
@ibayer it seems that it works! This is the output after running make http://pastie.org/private/wmj49h48dc6erxmgt2euq

**Comment by ibayer** [comment] 2015-08-10 02:22
@rakandirbas 
Great, can you try to run the tests too `cd fastfm-core/src/test; make; make check`

**Comment by rakandirbas** [comment] 2015-08-11 20:04
@ibayer didn't work! http://pastie.org/private/vhawksatpw2fiqbhf4ohq

**Comment by colemast** [comment] 2015-08-11 23:02
I managed to get all the tests passing just by commenting out the feenableexcept lines. I believe there is a port of these to OSX but I haven't been able to find them tonight

**Comment by ibayer** [comment] 2015-08-12 04:41
Thanks guys.
@rakandirbas should be fine now.
@colemast  I meant to comment them out but missed some. The tests should be fine without the function. I only useful it to locating floating point errors, so we should be good without  OSX port.

**Closed as completed** 2015-10-05 13:41 UTC
Labels: help wanted
